---
apiVersion: v1
kind: Secret
metadata:
  name: kea-dhcp4-config
  namespace: metal3
type: Opaque
stringData:
  kea-dhcp4.conf: |
    {
      "Dhcp4": {
        "lease-database": {
          "type": "postgresql",
          "host": "kea-postgres-rw",
          "name": "kea",
          "user": "kea",
          "password": "changeme"
        },
        "hosts-database": {
          "type": "postgresql",
          "host": "kea-postgres-rw",
          "name": "kea",
          "user": "kea",
          "password": "changeme"
        },
        "hooks-libraries": [
          { "library": "/usr/lib/kea/hooks/libdhcp_pgsql.so" }
        ],
        "host-reservation-identifiers": ["hw-address"],
        "interfaces-config": {
          "interfaces": ["bond0.4002"],
          "dhcp-socket-type": "raw"
        },
        "control-sockets": [
          {
            "socket-type": "unix",
            "socket-name": "/var/run/kea/kea4-ctrl-socket"
          },
          {
            "socket-address": "0.0.0.0",
            "socket-port": 8000,
            "socket-type": "http"
          }
        ],
        "subnet4": [
          {
            "id": 1,
            "subnet": "10.16.28.0/24",
            "pools": [],
            "reservations-global": false,
            "reservations-in-subnet": true,
            "reservations-out-of-pool": true
          }
        ],
        "loggers": [
          {
            "name": "kea-dhcp4",
            "severity": "INFO",
            "output_options": [
              { "output": "stdout" }
            ]
          }
        ]
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kea-dhcp
  namespace: metal3
  labels:
    app: kea-dhcp
spec:
  selector:
    matchLabels:
      app: kea-dhcp
  template:
    metadata:
      labels:
        app: kea-dhcp
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        ironic-conductor: enabled
      tolerations:
        - key: sunet.se/ironic-conductor
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kea-dhcp4
          image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.7.9
          ports:
            - containerPort: 8000
              name: ctrl-api
          volumeMounts:
            - name: kea-config
              mountPath: /etc/kea
          resources:
            requests:
              cpu: 100m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 192Mi
      volumes:
        - name: kea-config
          secret:
            secretName: kea-dhcp4-config
